# Generated by Django 5.0.14 on 2026-01-20 20:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circuits', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('nights', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('room_type', models.CharField(max_length=100)),
                ('number_of_rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('booking_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('includes_breakfast', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='circuits.group')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_bookings', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Hotel Booking',
                'verbose_name_plural': 'Hotel Bookings',
                'db_table': 'hotels',
                'ordering': ['group', 'check_in_date'],
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('twin', 'Twin'), ('triple', 'Triple'), ('suite', 'Suite')], max_length=20)),
                ('passengers', models.JSONField(default=list, help_text='Array of passenger IDs')),
                ('special_requests', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='operations.hotel')),
            ],
            options={
                'verbose_name': 'Accommodation',
                'verbose_name_plural': 'Accommodations',
                'db_table': 'accommodations',
                'ordering': ['hotel', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='SpecialService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('guide', 'Guide Service'), ('entrance', 'Entrance Fee'), ('activity', 'Activity'), ('meal', 'Meal'), ('show', 'Show/Event'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('service_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('booking_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_people', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_services', to='circuits.group')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='special_service_bookings', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Special Service',
                'verbose_name_plural': 'Special Services',
                'db_table': 'special_services',
                'ordering': ['group', 'service_date'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('staff_type', models.CharField(choices=[('guide', 'Tour Guide'), ('driver', 'Driver'), ('coordinator', 'Coordinator'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('languages', models.JSONField(default=list, help_text='Array of language codes')),
                ('certifications', models.TextField(blank=True)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('rate_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff',
                'db_table': 'staff',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['staff_type', 'status'], name='staff_staff_t_2e786c_idx'), models.Index(fields=['phone'], name='staff_phone_b34f7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('role', models.CharField(help_text='e.g., Main Guide, Driver, etc.', max_length=100)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='circuits.group')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='operations.staff')),
            ],
            options={
                'verbose_name': 'Staff Assignment',
                'verbose_name_plural': 'Staff Assignments',
                'db_table': 'staff_assignments',
                'ordering': ['group', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport_type', models.CharField(choices=[('bus', 'Bus'), ('van', 'Van'), ('car', 'Car'), ('train', 'Train'), ('boat', 'Boat'), ('other', 'Other')], max_length=20)),
                ('vehicle_description', models.CharField(blank=True, max_length=200)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('pickup_datetime', models.DateTimeField()),
                ('dropoff_datetime', models.DateTimeField(blank=True, null=True)),
                ('booking_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('driver_name', models.CharField(blank=True, max_length=200)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportations', to='circuits.group')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_bookings', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Transportation',
                'verbose_name_plural': 'Transportation',
                'db_table': 'transportation',
                'ordering': ['group', 'pickup_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['group', 'check_in_date'], name='hotels_group_i_f7ebe7_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['supplier', 'status'], name='hotels_supplie_2407db_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['booking_reference'], name='hotels_booking_ce6364_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['hotel'], name='accommodati_hotel_i_be5915_idx'),
        ),
        migrations.AddIndex(
            model_name='specialservice',
            index=models.Index(fields=['group', 'service_date'], name='special_ser_group_i_6bf495_idx'),
        ),
        migrations.AddIndex(
            model_name='specialservice',
            index=models.Index(fields=['service_type', 'status'], name='special_ser_service_b792c0_idx'),
        ),
        migrations.AddIndex(
            model_name='staffassignment',
            index=models.Index(fields=['group', 'start_date'], name='staff_assig_group_i_92b420_idx'),
        ),
        migrations.AddIndex(
            model_name='staffassignment',
            index=models.Index(fields=['staff', 'start_date'], name='staff_assig_staff_i_b7ea90_idx'),
        ),
        migrations.AddIndex(
            model_name='staffassignment',
            index=models.Index(fields=['payment_status'], name='staff_assig_payment_05e8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='transportation',
            index=models.Index(fields=['group', 'pickup_datetime'], name='transportat_group_i_216688_idx'),
        ),
        migrations.AddIndex(
            model_name='transportation',
            index=models.Index(fields=['supplier', 'status'], name='transportat_supplie_2d19e6_idx'),
        ),
    ]
