# Generated by Django 5.0.14 on 2026-01-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
