# Generated by Django 5.0.14 on 2026-01-20 20:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('date', models.DateField()),
                ('source', models.CharField(blank=True, help_text='e.g., SUNAT, BCR', max_length=100)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'db_table': 'exchange_rates',
                'ordering': ['-date', 'from_currency'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', 'date'], name='exchange_ra_from_cu_09af45_idx'), models.Index(fields=['date'], name='exchange_ra_date_cf7625_idx')],
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('supplier_type', models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('transport', 'Transport'), ('guide', 'Guide'), ('attraction', 'Attraction'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blacklisted', 'Blacklisted')], default='active', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='PER', max_length=3)),
                ('tax_id', models.CharField(blank=True, help_text='RUC or Tax ID', max_length=20)),
                ('payment_terms', models.CharField(blank=True, help_text='e.g., Net 30', max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=100)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'suppliers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='suppliers_code_e95fc6_idx'), models.Index(fields=['supplier_type', 'status'], name='suppliers_supplie_f7a2c2_idx'), models.Index(fields=['country', 'city'], name='suppliers_country_76c89b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('accommodation', 'Accommodation'), ('meal', 'Meal'), ('transport', 'Transport'), ('guide', 'Guide Service'), ('entrance', 'Entrance Fee'), ('activity', 'Activity'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('unit', models.CharField(blank=True, help_text='e.g., per person, per night', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('min_quantity', models.IntegerField(default=1)),
                ('max_quantity', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Service',
                'verbose_name_plural': 'Supplier Services',
                'db_table': 'supplier_services',
                'ordering': ['supplier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.CharField(choices=[('low', 'Low Season'), ('mid', 'Mid Season'), ('high', 'High Season'), ('peak', 'Peak Season')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('min_stay', models.IntegerField(blank=True, help_text='Minimum nights/days', null=True)),
                ('notes', models.TextField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_periods', to='suppliers.supplierservice')),
            ],
            options={
                'verbose_name': 'Price Period',
                'verbose_name_plural': 'Price Periods',
                'db_table': 'price_periods',
                'ordering': ['service', 'start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='supplierservice',
            index=models.Index(fields=['supplier', 'service_type'], name='supplier_se_supplie_7cfd32_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierservice',
            index=models.Index(fields=['is_active'], name='supplier_se_is_acti_a03fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='priceperiod',
            index=models.Index(fields=['service', 'start_date', 'end_date'], name='price_perio_service_09277b_idx'),
        ),
        migrations.AddIndex(
            model_name='priceperiod',
            index=models.Index(fields=['season'], name='price_perio_season_c94d30_idx'),
        ),
    ]
