# Generated by Django 5.0.14 on 2026-01-20 20:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circuits', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('passport', 'Passport'), ('visa', 'Visa'), ('insurance', 'Insurance'), ('itinerary', 'Itinerary'), ('voucher', 'Voucher'), ('ticket', 'Ticket'), ('photo', 'Photo'), ('report', 'Report'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'txt', 'csv', 'zip'])])),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('related_to', models.CharField(choices=[('group', 'Group'), ('passenger', 'Passenger'), ('supplier', 'Supplier'), ('general', 'General')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Document tags')),
                ('is_public', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='circuits.group')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='circuits.passenger')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='suppliers.supplier')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_type', 'related_to'], name='documents_documen_089567_idx'), models.Index(fields=['group', 'document_type'], name='documents_group_i_52406a_idx'), models.Index(fields=['passenger', 'document_type'], name='documents_passeng_505ddd_idx'), models.Index(fields=['supplier', 'document_type'], name='documents_supplie_0b2838_idx'), models.Index(fields=['is_archived', 'created_at'], name='documents_is_arch_1a0bdf_idx'), models.Index(fields=['expires_at'], name='documents_expires_111bd4_idx')],
            },
        ),
    ]
