# Generated by Django 5.0.14 on 2026-01-20 20:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('max_passengers', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_passengers', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'programs',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='programs_code_a0c867_idx'), models.Index(fields=['status'], name='programs_status_1f33ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('current_passengers', models.IntegerField(default=0)),
                ('max_passengers', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('tour_conductor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['tour_conductor', 'operations_manager', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_groups', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='circuits.program')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight_type', models.CharField(choices=[('outbound', 'Outbound'), ('return', 'Return'), ('domestic', 'Domestic')], max_length=20)),
                ('airline', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=20)),
                ('departure_airport', models.CharField(max_length=100)),
                ('departure_city', models.CharField(max_length=100)),
                ('departure_country', models.CharField(max_length=3)),
                ('arrival_airport', models.CharField(max_length=100)),
                ('arrival_city', models.CharField(max_length=100)),
                ('arrival_country', models.CharField(max_length=3)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('booking_reference', models.CharField(blank=True, max_length=50)),
                ('booking_status', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='circuits.group')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'db_table': 'flights',
                'ordering': ['group', 'departure_datetime'],
                'indexes': [models.Index(fields=['group', 'flight_type'], name='flights_group_i_95528d_idx'), models.Index(fields=['departure_datetime'], name='flights_departu_c63dbd_idx'), models.Index(fields=['booking_reference'], name='flights_booking_fcdff0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('breakfast_included', models.BooleanField(default=False)),
                ('lunch_included', models.BooleanField(default=False)),
                ('dinner_included', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='circuits.group')),
            ],
            options={
                'verbose_name': 'Itinerary Item',
                'verbose_name_plural': 'Itinerary',
                'db_table': 'itinerary',
                'ordering': ['group', 'day_number'],
                'indexes': [models.Index(fields=['group', 'date'], name='itinerary_group_i_0bcf4e_idx'), models.Index(fields=['group', 'day_number'], name='itinerary_group_i_b524dc_idx')],
                'unique_together': {('group', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('dni', 'DNI'), ('passport', 'Passport'), ('ruc', 'RUC'), ('other', 'Other')], max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('nationality', models.CharField(default='PER', max_length=3)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='reserved', max_length=20)),
                ('is_leader', models.BooleanField(default=False)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('special_requirements', models.TextField(blank=True)),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='circuits.group')),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
                'db_table': 'passengers',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['group', 'status'], name='passengers_group_i_a54447_idx'), models.Index(fields=['document_type', 'document_number'], name='passengers_documen_a52448_idx'), models.Index(fields=['email'], name='passengers_email_620f4f_idx')],
                'unique_together': {('group', 'document_type', 'document_number')},
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['code'], name='groups_code_af74e0_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['program', 'start_date'], name='groups_program_a11bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['status', 'start_date'], name='groups_status_c9ddde_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['tour_conductor'], name='groups_tour_co_a29c57_idx'),
        ),
    ]
